### ISSUE TITLE
Add a swagger package or documentation

### ISSUE THREAD

**Issue by titouancreach** [firenero/TypeId#14]
Hello,

An endpoint with a parameter or response containing a TypeId doesn't display properly in Swagger.
Because Swagger is not aware that we used a custom Converter (look at `items[].id`):

![image](https://github.com/firenero/TypeId/assets/3995719/f01bcc76-62c8-415c-8bc4-e1bb0263d144)

It's not a big deal because it's very simple to fix: 
 
```cs
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "api", Version = "v1" });

    c.UseAllOfToExtendReferenceSchemas();

    c.SchemaFilter<MaybeSchemaFilter>();

    c.MapType(typeof(TypeId), () => new OpenApiSchema { Type = "string", Example = new OpenApiString("prefix_01h93ech7jf5ktdwg6ye383x34") });
    c.MapType(typeof(TypeIdDecoded), () => new OpenApiSchema { Type = "string", Example = new OpenApiString("prefix_01h93ech7jf5ktdwg6ye383x34") });
});

```

After the fix, it works:
<img width="993" alt="Screenshot 2023-08-30 at 16 49 28" src="https://github.com/firenero/TypeId/assets/3995719/ef4276d7-9359-4be8-a6e3-925f6f5868c9">

I would like to know if you are interested to make a package containing an extension method (like for serialisation) or  maybe,
just add a few lines in the Readme. 

I can make a PR if interested anyway.

Thanks

**Comment by firenero** [comment]
Hi @titouancreach, thanks for reporting this. 

I feel like creating a separate package for just 2 lines of hints for swagger is an overkill. But adding this approach to docs is definitely helpful. Ideally, there should be a section about JSON serialization packages and swagger examples somewhere alongside these lines. 

I would appreciate if you could submit a PR with docs changes.
