### ISSUE TITLE
Support use of TypeId as Dictionary Key (system.text.json)

### ISSUE THREAD

**Issue by danspam** [firenero/TypeId#16]
The system.text.json customer converters do not override the methods `WriteAsPropertyName` and `ReadAsPropertyName`. This means that any attempt to use a TypeId as a dictionary key results in a `System.NotSupportedException` being thrown when serializing/deserializing.

**Comment by firenero** [comment]
Thanks for reporting and submitting PR @danspam. Sorry for taking so long to get back to you. I'm going to review the PR in a few hours and hopefully, we can merge it soon.

**Comment by firenero** [comment]
#17 was merged. The fix is available in [v1.0.0 on nuget](https://www.nuget.org/packages/FastIDs.TypeId.Serialization.SystemTextJson/1.0.0). Thanks again for your contribution @danspam
