### ISSUE TITLE
ISerializable

### ISSUE THREAD

**Issue by incompletude** [firenero/TypeId#28]
Is it possible to have TypeId to implement ISerializable or you think this is something out of scope and should be done internally?

**Comment by firenero** [comment]
I think it's possible to apply `[Serializable]` attribute to `TypeId` and `TypeIdDecoded` similarly to how it's done for `Guid` in .NET. I don't think there is a point in implementing `ISerializable` directly, unless I'm missing something.

Feel free to submit a PR with this change and I'll be happy to review and merge it. Please note, that this change would also require adding some unit tests.
